import Layout from '@/components/Layout';
import Loader from '@/components/Loader';
import Navbar from '@/components/Navbar';
import { useGlobal } from '@/store/globals';
import '@/styles/globals.css';
import { AnimatePresence } from 'framer-motion';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function App({ Component, pageProps }: AppProps) {
  const isLoading = useGlobal((state) => state.loader);
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Jonah Louis</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {!isLoading ? <Navbar /> : null}
      <AnimatePresence mode='wait'>
        {isLoading ? (
          <Loader key='loader' />
        ) : (
          <Component {...pageProps} key={router.pathname} />
        )}
      </AnimatePresence>
    </>
  );
}
